### ISSUE TITLE
[Bug]: Config search fails if there is a file named `.config`

### ISSUE THREAD

**Issue by Lightning00Blade** [cosmiconfig/cosmiconfig#313]
Minimal, reproducible example:
Create file `getConfig.mjs`
```js
import { cosmiconfigSync } from 'cosmiconfig';

const config = cosmiconfigSync('tester').search();
console.log(config);
```
Create a empty `.config` file.
```bash
touch .config
```
Execute the  `getConfig.mjs`.

Expected behavior:
`config` variable is `null` 
Actual behavior:
Error is show as such 
```
node:fs:592
  handleErrorFromBinding(ctx);
  ^

Error: ENOTDIR: not a directory, open '/usr/local/google/home/nvitkov/testing/config/tester/.config/testerrc'
    at Object.openSync (node:fs:592:3)
    at Object.readFileSync (node:fs:460:35)
    at readFileSync (/usr/local/google/home/nvitkov/testing/config/tester/node_modules/cosmiconfig/dist/readFile.js:45:33)
    at ExplorerSync.loadSearchPlaceSync (/usr/local/google/home/nvitkov/testing/config/tester/node_modules/cosmiconfig/dist/ExplorerSync.js:74:48)
    at ExplorerSync.searchDirectorySync (/usr/local/google/home/nvitkov/testing/config/tester/node_modules/cosmiconfig/dist/ExplorerSync.js:60:32)
    at run (/usr/local/google/home/nvitkov/testing/config/tester/node_modules/cosmiconfig/dist/ExplorerSync.js:41:27)
    at cacheWrapperSync (/usr/local/google/home/nvitkov/testing/config/tester/node_modules/cosmiconfig/dist/cacheWrapper.js:28:18)
    at ExplorerSync.searchFromDirectorySync (/usr/local/google/home/nvitkov/testing/config/tester/node_modules/cosmiconfig/dist/ExplorerSync.js:52:49)
    at ExplorerSync.searchSync (/usr/local/google/home/nvitkov/testing/config/tester/node_modules/cosmiconfig/dist/ExplorerSync.js:34:17)
    at file:///usr/local/google/home/nvitkov/testing/config/tester/getConfig.mjs:3:42 {
  errno: -20,
  syscall: 'open',
  code: 'ENOTDIR',
  path: '/usr/local/google/home/nvitkov/testing/config/tester/.config/testerrc'
}

Node.js v20.3.1
```

The issue is the default `searchPlaces` are passed in https://github.com/cosmiconfig/cosmiconfig/blob/main/src/index.ts#L188
Include a path, that is never checked if it's a file.

**Comment by jrandolf** [comment]
Fixed in the refactor.

**Comment by kapetan** [comment]
This issue is still present in version 8.3.5. The problem seems to be line: https://github.com/cosmiconfig/cosmiconfig/blob/8550adb3da7c91866b3a8862b5b5caf42866b0a4/src/ExplorerSync.ts#L51

It's missing a check for `ENOTDIR`.

**Comment by d-fischer** [comment]
Now properly fixed (and tested!) with 8.3.6.
